const { getJestProjects } = require('@nrwl/jest');

module.exports = {
  projects: [
    ...getJestProjects(),
    '<rootDir>/apps/ria',
    '<rootDir>/libs/breaking-news',
    '<rootDir>/apps/api',
    '<rootDir>/libs/interfaces',
    '<rootDir>/libs/trading/domain',
    '<rootDir>/apps/trading',
    '<rootDir>/libs/trading/feature-trade-center',
    '<rootDir>/libs/shared/ui-trading',
    '<rootDir>/libs/shared/ui-integration',
    '<rootDir>/apps/ui-integration',
    '<rootDir>/apps/testme',
    '<rootDir>/libs/shared/aws-integration',
    '<rootDir>/libs/footer',
    '<rootDir>/libs/shared/investing',
    '<rootDir>/libs/header',
    '<rootDir>/apps/investing-elements',
    '<rootDir>/libs/shared/material',
    '<rootDir>/libs/center',
    '<rootDir>/libs/settings',
    '<rootDir>/libs/layout',
    '<rootDir>/libs/home',
    '<rootDir>/libs/investing',
    '<rootDir>/apps/ria-react',
    '<rootDir>/libs/bonds',
    '<rootDir>/libs/security',
    '<rootDir>/libs/trading/feature-allocation',
    '<rootDir>/libs/shared/ui-allocation',
    '<rootDir>/apps/ui-allocation',
    '<rootDir>/libs/shared/ag-grid',
    '<rootDir>/libs/trading/feature-trade-blotter',
    '<rootDir>/libs/trading/feature-app-load',
    '<rootDir>/libs/shared/loader',
    '<rootDir>/libs/trading/feature-trade-entry',
    '<rootDir>/libs/options/domain',
    '<rootDir>/apps/options',
    '<rootDir>/libs/options/feature-orders',
    '<rootDir>/libs/shared/core',
    '<rootDir>/libs/trading/shared-allocations'
  ]
};
